### ISSUE TITLE
[Feature] Add language support

### ISSUE THREAD

**Issue by hiroshimorowaka** [jotavetech/baseschallenge#3]
### Description
It would be interesting to add support for other languages, but initially starting with English (current) and Portuguese.

### Implementation suggestion

We could add language configuration files, such as Json's to add keys related to the field and the value with the translation itself. 

Something like:

- pt-BR
main_page: {
  "faq_title": "Perguntas frequentes"
   ...
}

- en-US
main_page: {
  "faq_title": "Frequently asked questions"
   ...
}

What do you think?

**Comment by joao-gugel** [comment]
I think it would be nice, make a translation to portuguese may increase the number of people that we can achieve, improving the porpouse of this game. 

I make something like that in my website https://jotave.tech, which allows the user to see an en-us and pt-br version.

I will keep this issue open to implement this feature in the near future or merge a pull request.

tnx Guilherme 😊
